apiVersion: v1
kind: Pod
metadata:
  name: connection-test
  labels:
    app: test
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
  restartPolicy: Never