apiVersion: v1
kind: Service
metadata:
  name: web-nodeport
  labels:
    app: web-external
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - port: 80        # Internal service port
    targetPort: 80  # Container port
    nodePort: 30081 # External port (30000-32767)
    protocol: TCP
    name: http