apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
  labels:
    app: web-lb
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  # On Docker Desktop, LoadBalancer works like NodePort
  # On clouds (AWS, GCP, Azure), creates a real Load Balancer