apiVersion: v1
kind: Pod
metadata:
  name: app-with-sidecar
  labels:
    app: multi-container-example
spec:
  containers:
  # Main container - web application
  - name: web-app
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log/nginx
  
  # Sidecar container - log collector
  - name: log-collector
    image: busybox
    command: ["sh", "-c"]
    args:
    - |
      while true; do
        echo "$(date): Collecting logs..." >> /shared/collector.log
        if [ -f /shared/access.log ]; then
          tail -n 5 /shared/access.log >> /shared/collector.log
        fi
        sleep 10
      done
    volumeMounts:
    - name: shared-logs
      mountPath: /shared
  
  volumes:
  - name: shared-logs
    emptyDir: {}